from typing import Union
from linter.helpers import snake_case_to_pascal_case
from linter.rule import ParamSet, Rule, Severity

from linter.rules.field_requires_description import FieldRequiresDescription
from linter.rules.view_with_many_fields_requires_fields_hidden_by_default import ViewWithManyFieldsRequiresFieldsHiddenByDefault
from linter.rules.view_with_dimensions_and_measures_has_one_primary_key import ViewWithDimensionsAndMeasuresHasOnePrimaryKey
from linter.rules.dimension_group_of_type_time_requires_datatype import DimensionGroupOfTypeTimeRequiresDatatype
from linter.rules.dimension_group_of_type_time_requires_timeframes import DimensionGroupOfTypeTimeRequiresTimeframes
from linter.rules.explore_requires_description import ExploreRequiresDescription
from linter.rules.explore_joins_require_relationship import ExploreJoinsRequireRelationship
from linter.rules.explore_joins_contain_many_to_many_relationship import ExploreJoinsContainManyToManyRelationship
from linter.rules.explore_requires_label import ExploreRequiresLabel
from linter.rules.field_sql_html_requires_user_attribute_when_search_terms_found_exact import FieldSqlHtmlRequiresUserAttributeWhenSearchTermsFoundExact
from linter.rules.field_name_is_snake_case import FieldNameIsSnakeCase
from linter.rules.view_name_is_snake_case import ViewNameIsSnakeCase
from linter.rules.explore_requires_always_filter import ExploreRequiresAlwaysFilter
from linter.rules.explore_requires_fields import ExploreRequiresFields
from linter.rules.primary_key_is_first_dimension_in_view import PrimaryKeyIsFirstDimensionInView
from linter.rules.view_requires_label import ViewRequiresLabel
from linter.rules.dimension_group_name_should_not_end_with_date_or_time import DimensionGroupNameShouldNotEndWithDateOrTime
from linter.rules.dimension_group_name_should_not_end_with import DimensionGroupNameShouldNotEndWith
from linter.rules.yesno_field_label_should_not_contain_yesno import YesnoFieldLabelShouldNotContainYesno
from linter.rules.count_measure_name_must_start_with_count import CountMeasureNameMustStartWithCount
from linter.rules.average_measure_name_must_start_with_avg_or_average import AverageMeasureNameMustStartWithAvgOrAverage
from linter.rules.sum_measure_name_must_start_with_sum_or_total import SumMeasureNameMustStartWithSumOrTotal
from linter.rules.yesno_field_name_must_start_with_is_or_has import YesnoFieldNameMustStartWithIsOrHas
from linter.rules.explore_tag_requires_owner import ExploreTagRequiresOwner
from linter.rules.include_should_not_have_views_with_wildcard import IncludeShouldNotHaveViewsWithWildcard
from linter.rules.view_must_have_unique_sql_table_name import ViewMustHaveUniqueSqlTableName
from linter.rules.label_custom_check import LabelCustomCheck
from linter.rules.label_is_camel_case import LabelIsCamelCase
from linter.rules.count_distinct_measure_name import CountDistinctMeasureName
from linter.rules.primary_key_prefix_and_is_hidden import PrimaryKeyPrefixAndIsHidden

class RuleFactory:
    def __init__(self) -> None:
        pass

    def build(self, rule_name: str, severity: Severity, params: Union[ParamSet, None] = None) -> Rule:
        classname = snake_case_to_pascal_case(rule_name)
        return globals()[classname](severity, params)
