from typing import Union
from linter.helpers import snake_case_to_pascal_case
from linter.rule import ParamSet, Rule, Severity

# TODO: AUTO-IMPORT RULES
from linter.rules.field_requires_description import FieldRequiresDescription
from linter.rules.view_with_many_fields_requires_fields_hidden_by_default import ViewWithManyFieldsRequiresFieldsHiddenByDefault
from linter.rules.view_with_dimensions_and_measures_has_one_primary_key import ViewWithDimensionsAndMeasuresHasOnePrimaryKey
from linter.rules.dimension_group_of_type_time_requires_datatype import DimensionGroupOfTypeTimeRequiresDatatype
from linter.rules.dimension_group_of_type_time_requires_timeframes import DimensionGroupOfTypeTimeRequiresTimeframes
from linter.rules.explore_requires_description import ExploreRequiresDescription
from linter.rules.explore_joins_require_relationship import ExploreJoinsRequireRelationship
from linter.rules.explore_joins_contain_many_to_many_relationship import ExploreJoinsContainManyToManyRelationship
from linter.rules.explore_requires_label import ExploreRequiresLabel
from linter.rules.field_sql_html_requires_user_attribute_when_search_terms_found_exact import FieldSqlHtmlRequiresUserAttributeWhenSearchTermsFoundExact
from linter.rules.field_name_is_snake_case import FieldNameIsSnakeCase
from linter.rules.view_name_is_snake_case import ViewNameIsSnakeCase
from linter.rules.explore_requires_always_filter import ExploreRequiresAlwaysFilter
from linter.rules.explore_requires_fields import ExploreRequiresFields
from linter.rules.primary_key_is_first_dimension_in_view import PrimaryKeyIsFirstDimensionInView
from linter.rules.count_measure_name_must_start_with_count import CountMeasureNameMustStartWithCount
from linter.rules.average_measure_name_must_start_with_avg_or_average import AverageMeasureNameMustStartWithAvgOrAverage
from linter.rules.sum_measure_name_must_start_with_sum_or_total import SumMeasureNameMustStartWithSumOrTotal
from linter.rules.yesno_field_name_must_start_with_is_or_has import YesnoFieldNameMustStartWithIsOrHas
from linter.rules.explore_tag_requires_owner import ExploreTagRequiresOwner
from linter.rules.model_file_should_not_have_wildcard_view_includes import ModelFileShouldNotHaveWildcardViewIncludes


class RuleFactory:
    def __init__(self) -> None:
        pass

    def build(self, rule_name: str, severity: Severity, params: Union[ParamSet, None] = None) -> Rule:
        classname = snake_case_to_pascal_case(rule_name)
        return globals()[classname](severity, params)
